### ISSUE TITLE
Can't figure out how to fix `Cannot read property '_innerValidate' of undefined`

### ISSUE THREAD

**Issue by Yattol** [pelotom/runtypes#270]
Hello guys,

I have a problem with a check and I can't figure out the reason.
I've tried to follow what runtypes does when `check` is called and it seems like everything is in the right place. I have tried searching around if anyone had a similar problem with no success.

I open this issue as a last resort, can anyone kindly give me some help? :)
Thank you very much!

This is the type I defined:
```
const payloadRecord = Record({
  name: String,
  apiKey: String,
  organizationId: String,
  autoAssignMode:  Union(Literal("something1"), Literal("something_else1")),
  requirements: RequirementsType,
  integrationType: Union(Literal("something2"), Literal("something_else2"))
})
```
RequirementsType is: 
```
Record({
    signature: Boolean,
    photograph: Boolean,
    notes: Boolean,
    minimumAge: Number,
 })
```
I'm passing the following object:
```
payloadRecord.check({
  name: "Test Name",
  apiKey: "test-api-key",
  organizationId: "random-organization-id",
  autoAssignMode: "something1",
  requirements: {
     signature: true,
     photograph: true,
     notes: true,
     minimumAge: 18,
},
integrationType: "something2",
})
```

And I keep receiving this error:
```
TypeError: Cannot read property '_innerValidate' of undefined
      at Object.innerValidate (node_modules/runtypes/lib/runtype.js:53:23)
      at InternalRecord.runtype_1.create.tag (node_modules/runtypes/lib/types/record.js:19:43)
      at Object.A._innerValidate (node_modules/runtypes/lib/runtype.js:13:16)
      at Object.A.validate (node_modules/runtypes/lib/runtype.js:15:46)
      at Object.check (node_modules/runtypes/lib/runtype.js:26:27)
      at Context.<anonymous> (test/something.test.ts:69:35)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

My setup is:
- runtypes '5.1.0'
- npm: '7.14.0'
- node: '12.18.4' 

Any idea? Let me know if you need additional information.

Thank you!

**Comment by Yattol** [comment]
A small update:

- I updated my setup like this:

```
runtypes '5.1.0'
npm: '7.14.0'
node: '12.18.4'
```
And the error message changed in:
```
TypeError: Cannot read property 'reflect' of undefined
      at /home/project/node_modules/runtypes/lib/types/record.js:45:55
      at Array.reduce (<anonymous>)
      at /home/project/node_modules/runtypes/lib/types/record.js:40:28
      at Object.A._innerValidate (node_modules/runtypes/lib/runtype.js:14:16)
      at Object.A.validate (node_modules/runtypes/lib/runtype.js:16:46)
      at Object.check (node_modules/runtypes/lib/runtype.js:29:24)
      at Function.create (src/fleet/fleet_command_builder.ts:230:66)
      at Context.<anonymous> (test/fleet/fleet_command_handler.test.ts:67:37)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)

```
The Record is the same. Still can't figure out what's going on

**Comment by yuhr** [comment]
Hmm, I can't reproduce any errors using the provided runtypes. The error messages sound like some runtypes you're using are not imported correctly in your test file (or some module file it depends on). Is `RequirementsType` really defined? Or have you correctly imported the runtypes? Have you tried cleaning up node_modules?

If possible, please provide a reproduction repository so I can investigate more precisely. But I guess this type of error should be caused by some kind of broken setup.

**Comment by yuhr** [comment]
Thanks zlumer! 👍🏻
